[project]
name = 'satscribe-contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.creator-registry-v6]
path = 'contracts/creator-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.revenue-splitter-v6]
path = 'contracts/revenue-splitter.clar'
clarity_version = 3
epoch = 'latest'

[contracts.subscription-nft-v6]
path = 'contracts/subscription-nft.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
